name: CI

on: [push, pull_request]

jobs:
  Linux:
    strategy:
      matrix:
        os:
          - runs-on: ubuntu-20.04
          - runs-on: ubuntu-18.04
    runs-on: ${{ matrix.os.runs-on }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Restore pyenv cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo
          ~/.pyenv
        key: pyenv-cache-${{ matrix.os.runs-on }}-${{ hashFiles('scripts/provision_*') }}
        restore-keys: pyenv-cache-${{ matrix.os.runs-on }}-
    - name: Restore pip cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
        key: pip-${{ matrix.os.runs-on }}-${{ hashFiles('requirements/*.txt') }}
        restore-keys: pip-${{ matrix.os.runs-on }}-
    - name: Install dependencies
      run: SKIP_DOCKER_INSTALL=1 scripts/provision_devtools.sh
    - name: Test
      run: |
        source ~/.bash_profile
        make test
    - name: Build
      run: |
        source ~/.bash_profile
        make all
    - name: Verify
      run: |
        xvfb-run -a dist/Tahoe-LAFS/tahoe --version-and-path
        xvfb-run -a dist/Gridsync/gridsync --version
        xvfb-run -a dist/Gridsync.AppImage --version
    - name: Test determinism
      run: |
        source ~/.bash_profile
        make test-determinism
    - name: Build (in container)
      run: |
        source ~/.bash_profile
        make clean in-container
    - name: Verify (on host)
      run: |
        xvfb-run -a dist/Gridsync.AppImage --version
    - name: sha256sum
      run: python3 scripts/sha256sum.py dist/*.*
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: dist/Gridsync.AppImage
        name: Gridsync-${{ matrix.os.runs-on }}.AppImage
  macOS:
    strategy:
      matrix:
        os:
          - runs-on: macos-11.0
          - runs-on: macos-10.15
    runs-on: ${{ matrix.os.runs-on }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Restore pyenv cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo
          ~/.pyenv
        key: pyenv-${{ matrix.os.runs-on }}-${{ hashFiles('scripts/provision_*') }}
        restore-keys: pyenv-${{ matrix.os.runs-on }}-
    - name: Restore pip cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
        key: pip-${{ matrix.os.runs-on }}-${{ hashFiles('requirements/*.txt') }}
        restore-keys: pip-${{ matrix.os.runs-on }}-
    - name: Install dependencies
      run: |
        sudo rm -rf /Applications/Python*
        scripts/provision_devtools.sh
    - name: Test
      run: |
        source ~/.bashrc
        make test
    - name: Make pyinstaller
      run: |
        source ~/.bashrc
        make pyinstaller
        make zip
    - name: Verify
      run: |
        dist/Gridsync.app/Contents/MacOS/Tahoe-LAFS/tahoe --version-and-path
        dist/Gridsync.app/Contents/MacOS/Gridsync --version
    - name: Test determinism
      run: |
        source ~/.bashrc
        make test-determinism
    - name: Make dmg
      run: |
        source ~/.bashrc
        make dmg
    - name: sha256sum
      run: python3 scripts/sha256sum.py dist/*.*
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: dist/Gridsync.dmg
        name: Gridsync-${{ matrix.os.runs-on }}.dmg
  Windows:
    strategy:
      matrix:
        os:
          - runs-on: windows-2019
    runs-on: ${{ matrix.os.runs-on }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Restore pip cache
      uses: actions/cache@v2
      with:
        path: c:\users\runneradmin\appdata\local\pip\cache
        key: pip-${{ matrix.os.runs-on }}-${{ hashFiles('requirements/*.txt') }}
        restore-keys: pip-${{ matrix.os.runs-on }}-
    - name: Install dependencies
      run: py -3 -m pip install tox diffoscope
    - name: Test
      run: .\make.bat test
    - name: Make pyinstaller
      run: |
        .\make.bat pyinstaller
        .\make.bat zip
    - name: Verify
      run: |
        .\dist\Gridsync\Tahoe-LAFS\tahoe.exe --version-and-path
        .\dist\Gridsync\Gridsync.exe --version
    - name: Test determinism
      run: |
        .\make.bat test-determinism
    - name: Make installer
      run: |
        .\make.bat installer
    - name: sha256sum
      run: python3 scripts/sha256sum.py .\dist\*.*
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: .\dist\Gridsync-setup.exe
        name: Gridsync-${{ matrix.os.runs-on }}-setup.exe
